export const coursesData = [
  {
    title: "Web Development",
    description: "Build beautiful responsive websites and dynamic web applications using modern web technologies.",
    duration: "6 Months",
    level: "Beginner to Advanced",
    emoji: "💻",
    price: 1999,
    videos: [
      { title: "HTML5 Basics - Structure & Tags", url: "https://www.youtube.com/embed/UB1O30fR-EE", duration: "20:15" },
      { title: "CSS3 - Flexbox & Grid Layouts", url: "https://www.youtube.com/embed/3elGSZSWTbM", duration: "25:30" },
      { title: "JavaScript ES6+ Features", url: "https://www.youtube.com/embed/nZ1DMMsyVyI", duration: "30:00" },
      { title: "React JS - Hooks & Context API", url: "https://www.youtube.com/embed/O6P86uwfdR0", duration: "35:45" },
      { title: "Node.js & Express REST API", url: "https://www.youtube.com/embed/Oe421EPjeBE", duration: "28:20" },
      { title: "MongoDB & Mongoose Databases", url: "https://www.youtube.com/embed/42T31aFOVVo", duration: "22:10" },
    ],
  },
  {
    title: "Data Science",
    description: "Analyze, visualize, and extract valuable insights from complex data structures using python.",
    duration: "8 Months",
    level: "Intermediate",
    emoji: "📊",
    price: 2499,
    videos: [
      { title: "Python for Data Science", url: "https://www.youtube.com/embed/LHBE6p9EcvI", duration: "18:45" },
      { title: "Pandas & NumPy Masterclass", url: "https://www.youtube.com/embed/vmEHCJofslg", duration: "32:20" },
      { title: "Data Visualization with Matplotlib", url: "https://www.youtube.com/embed/UO98lJQ3QGI", duration: "26:10" },
      { title: "SQL for Data Analysis", url: "https://www.youtube.com/embed/7S_tz1z_5bA", duration: "24:30" },
      { title: "Statistics & Probability", url: "https://www.youtube.com/embed/xxpc-HPKN28", duration: "28:15" },
      { title: "Intro to Machine Learning", url: "https://www.youtube.com/embed/Gv9_4yMHFhI", duration: "35:00" },
    ],
  },
  {
    title: "Machine Learning",
    description: "Master algorithms that learn from data and make predictions using industrial ML toolkits.",
    duration: "6 Months",
    level: "Advanced",
    emoji: "🤖",
    price: 3499,
    videos: [
      { title: "ML Fundamentals & Types", url: "https://www.youtube.com/embed/ukzFI9rgwfU", duration: "18:00" },
      { title: "Regression Algorithms", url: "https://www.youtube.com/embed/Vs7tn5VmfrA", duration: "28:30" },
      { title: "Decision Trees & Random Forests", url: "https://www.youtube.com/embed/7VeUPuFGJHk", duration: "22:45" },
      { title: "Feature Engineering", url: "https://www.youtube.com/embed/xy9e4WzH3Tc", duration: "20:10" },
      { title: "TensorFlow & PyTorch Basics", url: "https://www.youtube.com/embed/tpCFfeUEGs8", duration: "35:20" },
      { title: "Model Deployment as APIs", url: "https://www.youtube.com/embed/8P2O3f7C4oY", duration: "26:15" },
    ],
  },
  {
    title: "Deep Learning",
    description: "Dive deep into artificial neural networks, computer vision, and speech processing technologies.",
    duration: "5 Months",
    level: "Advanced",
    emoji: "🧠",
    price: 3999,
    videos: [
      { title: "Neural Networks & Backpropagation", url: "https://www.youtube.com/embed/aircAruvnKk", duration: "30:00" },
      { title: "CNN for Image Recognition", url: "https://www.youtube.com/embed/2S6A9m2gpN8", duration: "28:45" },
      { title: "RNN & LSTM Networks", url: "https://www.youtube.com/embed/YCzL96nL7j0", duration: "32:10" },
      { title: "Generative Adversarial Networks", url: "https://www.youtube.com/embed/8L11aMN5EY8", duration: "25:30" },
      { title: "PyTorch Deep Dive", url: "https://www.youtube.com/embed/c36lUUr864M", duration: "40:20" },
      { title: "Transfer Learning", url: "https://www.youtube.com/embed/yofjFQddwHE", duration: "22:00" },
    ],
  },
  {
    title: "Cyber Security",
    description: "Secure digital assets, perform ethical hacking, and protect networks from cyber threats.",
    duration: "6 Months",
    level: "Intermediate",
    emoji: "🔒",
    price: 2999,
    videos: [
      { title: "Cyber Security Foundations", url: "https://www.youtube.com/embed/z5nx9BOq-T4", duration: "22:15" },
      { title: "Ethical Hacking Basics", url: "https://www.youtube.com/embed/2z1J89WjLZY", duration: "35:40" },
      { title: "Cryptography & PKI", url: "https://www.youtube.com/embed/6_Cxj5WKpIw", duration: "28:20" },
      { title: "Linux Security & Bash", url: "https://www.youtube.com/embed/3GxrHj7Si5c", duration: "25:10" },
      { title: "Web Application Hacking", url: "https://www.youtube.com/embed/2TofunAI6fU", duration: "32:00" },
      { title: "Incident Response", url: "https://www.youtube.com/embed/e0/p5nAwOjY", duration: "20:45" },
    ],
  },
  {
    title: "Cloud Computing",
    description: "Deploy, manage, and scale server infrastructure on AWS, Azure, and Google Cloud Platform.",
    duration: "4 Months",
    level: "Intermediate",
    emoji: "☁️",
    price: 2799,
    videos: [
      { title: "Cloud Infrastructure Models", url: "https://www.youtube.com/embed/2LaAJq1lB1Q", duration: "18:30" },
      { title: "AWS EC2, S3 & RDS", url: "https://www.youtube.com/embed/a2TYgN1F7Uo", duration: "32:15" },
      { title: "Docker Containerization", url: "https://www.youtube.com/embed/3c-iBn73dDE", duration: "28:45" },
      { title: "Kubernetes Orchestration", url: "https://www.youtube.com/embed/s_o8dw7RZfQ", duration: "35:20" },
      { title: "Serverless Architecture", url: "https://www.youtube.com/embed/vb8Eb6hgNOQ", duration: "22:10" },
      { title: "Cloud Security Best Practices", url: "https://www.youtube.com/embed/1Ld3v5H9Y3I", duration: "24:30" },
    ],
  },
  {
    title: "Mobile App Development",
    description: "Build high-performance, cross-platform Android and iOS applications with single codebase.",
    duration: "6 Months",
    level: "Beginner to Advanced",
    emoji: "📱",
    price: 3299,
    videos: [
      { title: "JavaScript/Dart Fundamentals", url: "https://www.youtube.com/embed/WmR5IMm9_vk", duration: "20:00" },
      { title: "React Native Setup & Basics", url: "https://www.youtube.com/embed/0-S5a0eXPoc", duration: "28:30" },
      { title: "Mobile UI Design Principles", url: "https://www.youtube.com/embed/8HdWz3RjEMc", duration: "25:15" },
      { title: "State Management with Redux", url: "https://www.youtube.com/embed/9boMnm5X9-k", duration: "32:40" },
      { title: "API Integration in Mobile Apps", url: "https://www.youtube.com/embed/6IfRCjZTPbA", duration: "26:10" },
      { title: "App Store & Play Store Publishing", url: "https://www.youtube.com/embed/8zCJ5H3YyDA", duration: "18:45" },
    ],
  },
  {
    title: "Database Management",
    description: "Design and implement relational and non-relational database storage systems for high throughput.",
    duration: "4 Months",
    level: "Beginner to Intermediate",
    emoji: "🗄️",
    price: 1799,
    videos: [
      { title: "Relational Database Design", url: "https://www.youtube.com/embed/HXV3zeQKqFQ", duration: "22:30" },
      { title: "Advanced SQL Queries", url: "https://www.youtube.com/embed/7S_tz1z_5bA", duration: "30:15" },
      { title: "NoSQL - MongoDB & Cassandra", url: "https://www.youtube.com/embed/xh4gyQ1eNQE", duration: "28:40" },
      { title: "Database Indexing & Performance", url: "https://www.youtube.com/embed/w0dC5XvAIpE", duration: "24:10" },
      { title: "Transactions & ACID Properties", url: "https://www.youtube.com/embed/4Z9KEBexzcM", duration: "20:20" },
      { title: "Backup & Recovery Strategies", url: "https://www.youtube.com/embed/1D5T7UqKl7U", duration: "18:55" },
    ],
  },
  {
    title: "Networking",
    description: "Configure switches, routers, and secure networks for large enterprises and setups.",
    duration: "4 Months",
    level: "Beginner to Intermediate",
    emoji: "🌐",
    price: 2199,
    videos: [
      { title: "TCP/IP & OSI Models", url: "https://www.youtube.com/embed/rYodcvhh7bQ", duration: "25:00" },
      { title: "IP Addressing & Subnetting", url: "https://www.youtube.com/embed/s_Ntt6eTn94", duration: "32:30" },
      { title: "Switching & VLANs", url: "https://www.youtube.com/embed/9eH16Fxeb9M", duration: "28:15" },
      { title: "Routing Protocols (OSPF, BGP)", url: "https://www.youtube.com/embed/7BxT3VnL4jQ", duration: "35:40" },
      { title: "NAT & Firewalls", url: "https://www.youtube.com/embed/FTUV0tVfY4Q", duration: "22:10" },
      { title: "CCNA Certification Prep", url: "https://www.youtube.com/embed/n2Mv_8KHBn0", duration: "30:20" },
    ],
  },
  {
    title: "Software Engineering",
    description: "Learn methodologies, architecture design patterns, and engineering practices used in tech industries.",
    duration: "5 Months",
    level: "Intermediate",
    emoji: "⚙️",
    price: 2599,
    videos: [
      { title: "SDLC & Agile Methodologies", url: "https://www.youtube.com/embed/-FpC7qx2TSI", duration: "22:15" },
      { title: "System Architecture & OOD", url: "https://www.youtube.com/embed/mg8F6U9RK7I", duration: "30:40" },
      { title: "Design Patterns Explained", url: "https://www.youtube.com/embed/v9ejT8FO-7I", duration: "35:20" },
      { title: "Testing & TDD", url: "https://www.youtube.com/embed/QCvE4GvUi-Q", duration: "28:10" },
      { title: "CI/CD Pipelines", url: "https://www.youtube.com/embed/CPbvxH6T1ls", duration: "24:45" },
      { title: "Code Refactoring Techniques", url: "https://www.youtube.com/embed/D4T2L0S7E0I", duration: "20:30" },
    ],
  },
  {
    title: "Artificial Intelligence",
    description: "Understand Natural Language Processing, computer vision, and build Large Language Model applications.",
    duration: "8 Months",
    level: "Advanced",
    emoji: "🔮",
    price: 4499,
    videos: [
      { title: "AI & Search Algorithms", url: "https://www.youtube.com/embed/4FjBjhGxJ34", duration: "25:30" },
      { title: "Natural Language Processing", url: "https://www.youtube.com/embed/fLvJ8Vd_HoQ", duration: "32:15" },
      { title: "Computer Vision Basics", url: "https://www.youtube.com/embed/kwZ2K70R7kV", duration: "28:40" },
      { title: "Large Language Models", url: "https://www.youtube.com/embed/izvF0arKOVA", duration: "35:00" },
      { title: "LangChain & Vector Databases", url: "https://www.youtube.com/embed/sVcwVQRHI1o", duration: "30:20" },
      { title: "AI Ethics & Future", url: "https://www.youtube.com/embed/8D6j7vGbkcs", duration: "22:10" },
    ],
  },
  {
    title: "Blockchain Development",
    description: "Code smart contracts, develop decentralized applications (DApps), and understand cryptography.",
    duration: "5 Months",
    level: "Advanced",
    emoji: "⛓️",
    price: 3799,
    videos: [
      { title: "Blockchain & Cryptography", url: "https://www.youtube.com/embed/SSo_EIwHSd4", duration: "24:15" },
      { title: "Ethereum & Solidity Basics", url: "https://www.youtube.com/embed/gyMwXuJrbJQ", duration: "35:40" },
      { title: "Web3.js & Ethers.js", url: "https://www.youtube.com/embed/p3jTq2RhDfM", duration: "28:20" },
      { title: "DApp Development", url: "https://www.youtube.com/embed/coa3veS1txc", duration: "32:10" },
      { title: "ERC-20 & ERC-721 Tokens", url: "https://www.youtube.com/embed/ppVY3iW2QqI", duration: "26:30" },
      { title: "Smart Contract Security", url: "https://www.youtube.com/embed/UMr1H7SLJqM", duration: "30:00" },
    ],
  },
  {
    title: "DevOps",
    description: "Automate build deployments, manage server configurations, and setup monitoring systems.",
    duration: "4 Months",
    level: "Intermediate",
    emoji: "🚀",
    price: 2899,
    videos: [
      { title: "DevOps Culture & Practices", url: "https://www.youtube.com/embed/0yWAtQ6U4Y8", duration: "18:45" },
      { title: "CI/CD with Jenkins & GitHub Actions", url: "https://www.youtube.com/embed/mFFCX8z7i_E", duration: "32:30" },
      { title: "Infrastructure as Code (Terraform)", url: "https://www.youtube.com/embed/l5k1ai_GBDE", duration: "28:15" },
      { title: "Ansible Configuration Management", url: "https://www.youtube.com/embed/1id6ERvfozo", duration: "24:40" },
      { title: "Prometheus & Grafana Monitoring", url: "https://www.youtube.com/embed/h4Sl21AKiDg", duration: "22:20" },
      { title: "ELK Stack Log Analytics", url: "https://www.youtube.com/embed/H0N3FQnSIlk", duration: "26:10" },
    ],
  },
  {
    title: "Python Programming",
    description: "Learn the most popular language for scripting, automation, web applications, and analytics.",
    duration: "3 Months",
    level: "Beginner to Advanced",
    emoji: "🐍",
    price: 1499,
    videos: [
      { title: "Python Basics", url: "https://www.youtube.com/embed/rfscVS0vtbw", duration: "22:00" },
      { title: "OOP in Python", url: "https://www.youtube.com/embed/JeznW_7DlB0", duration: "28:30" },
      { title: "File I/O & Error Handling", url: "https://www.youtube.com/embed/8Q6G1LxUqpk", duration: "20:15" },
      { title: "Web APIs & JSON", url: "https://www.youtube.com/embed/9P6r7jGBp7Q", duration: "24:40" },
      { title: "Web Scraping with BeautifulSoup", url: "https://www.youtube.com/embed/87Gx3T0W1cU", duration: "26:10" },
      { title: "Clean Code (PEP 8)", url: "https://www.youtube.com/embed/HQ3_p7kN8f4", duration: "18:20" },
    ],
  },
  {
    title: "Java Development",
    description: "Develop enterprise-scale backend web services using Java and Spring Boot framework.",
    duration: "6 Months",
    level: "Intermediate",
    emoji: "☕",
    price: 2999,
    videos: [
      { title: "Java OOP & Collections", url: "https://www.youtube.com/embed/grEKMHGYyns", duration: "26:15" },
      { title: "Multi-threading in Java", url: "https://www.youtube.com/embed/ENdOsO5SiEM", duration: "32:40" },
      { title: "Spring Boot Framework", url: "https://www.youtube.com/embed/vtPkZShrvXQ", duration: "35:20" },
      { title: "Spring Data JPA & Hibernate", url: "https://www.youtube.com/embed/Xvru6b1WsrE", duration: "28:30" },
      { title: "Microservices Architecture", url: "https://www.youtube.com/embed/j3XUf0g1IUk", duration: "30:10" },
      { title: "Testing with JUnit & Mockito", url: "https://www.youtube.com/embed/GEphRkAU_ZU", duration: "22:45" },
    ],
  },
  {
    title: "C & C++ Programming",
    description: "Understand low-level memory layout, pointers, and high-performance programming techniques.",
    duration: "4 Months",
    level: "Beginner to Advanced",
    emoji: "👾",
    price: 1699,
    videos: [
      { title: "C Basics & Control Structures", url: "https://www.youtube.com/embed/KJgsSFOSQv0", duration: "24:30" },
      { title: "Pointers & Memory Management", url: "https://www.youtube.com/embed/2ybLD6_2gKM", duration: "30:15" },
      { title: "OOP in C++", url: "https://www.youtube.com/embed/i_5pvt7ag7E", duration: "28:40" },
      { title: "STL Containers", url: "https://www.youtube.com/embed/R4n9JX1MGmY", duration: "26:20" },
      { title: "Data Structures", url: "https://www.youtube.com/embed/RBSGKlAvoiM", duration: "35:00" },
      { title: "Algorithms & Big-O", url: "https://www.youtube.com/embed/8hly31xKli0", duration: "22:10" },
    ],
  },
];
