export const coursesData = [
  {
    title: "Web Development",
    description: "Build beautiful responsive websites and dynamic web applications using modern web technologies.",
    duration: "6 Months",
    level: "Beginner to Advanced",
    emoji: "💻",
    syllabus: [
      "HTML5, CSS3, Flexbox & Grid Layouts",
      "Modern JavaScript (ES6+ Features)",
      "React JS (Hooks, Context API, Router)",
      "Node.js & Express RESTful APIs",
      "MongoDB & Mongoose Databases",
      "Git, GitHub & Cloud Deployment",
    ],
  },
  {
    title: "Data Science",
    description: "Analyze, visualize, and extract valuable insights from complex data structures using python.",
    duration: "8 Months",
    level: "Intermediate",
    emoji: "📊",
    syllabus: [
      "Python programming fundamentals",
      "Data Manipulation with Pandas & NumPy",
      "Data Visualization with Matplotlib & Seaborn",
      "SQL databases and data warehousing",
      "Applied Statistics & Probability",
      "Intro to Machine Learning Models",
    ],
  },
  {
    title: "Machine Learning",
    description: "Master algorithms that learn from data and make predictions using industrial ML toolkits.",
    duration: "6 Months",
    level: "Advanced",
    emoji: "🤖",
    syllabus: [
      "Supervised vs Unsupervised Learning",
      "Regression, Decision Trees & Random Forests",
      "Feature Engineering & Dimensionality Reduction",
      "TensorFlow and PyTorch basics",
      "Model Evaluation & Hyperparameter Tuning",
      "Deploying ML Models as Web APIs",
    ],
  },
  {
    title: "Deep Learning",
    description: "Dive deep into artificial neural networks, computer vision, and speech processing technologies.",
    duration: "5 Months",
    level: "Advanced",
    emoji: "🧠",
    syllabus: [
      "Multi-Layer Perceptrons & Backpropagation",
      "Convolutional Neural Networks (CNNs) for Images",
      "Recurrent Neural Networks (RNNs) & LSTMs",
      "Generative Adversarial Networks (GANs)",
      "PyTorch framework development",
      "Transfer Learning & Model Fine-tuning",
    ],
  },
  {
    title: "Cyber Security",
    description: "Secure digital assets, perform ethical hacking, and protect networks from cyber threats.",
    duration: "6 Months",
    level: "Intermediate",
    emoji: "🔒",
    syllabus: [
      "Networking Protocols & Cyber Security Foundations",
      "Ethical Hacking & Penetration Testing",
      "Cryptography, SSL/TLS, and PKI",
      "Linux Administration & Bash Scripting",
      "Web Application Hacking Techniques",
      "Incident Response & Vulnerability Assessment",
    ],
  },
  {
    title: "Cloud Computing",
    description: "Deploy, manage, and scale server infrastructure on AWS, Azure, and Google Cloud Platform.",
    duration: "4 Months",
    level: "Intermediate",
    emoji: "☁️",
    syllabus: [
      "Cloud Infrastructure Basics & Models",
      "AWS Core Services (EC2, S3, RDS, IAM)",
      "Containerization using Docker",
      "Container Orchestration with Kubernetes",
      "Serverless computing & Microservices",
      "Cloud Security & Compliance best practices",
    ],
  },
  {
    title: "Mobile App Development",
    description: "Build high-performance, cross-platform Android and iOS applications with single codebase.",
    duration: "6 Months",
    level: "Beginner to Advanced",
    emoji: "📱",
    syllabus: [
      "JavaScript/Dart Fundamentals",
      "React Native or Flutter Frameworks",
      "Mobile UI Design & Gesture Handlers",
      "State Management (Redux/Provider)",
      "Integrating APIs & Native Device Features",
      "App Store & Google Play Publishing",
    ],
  },
  {
    title: "Database Management",
    description: "Design and implement relational and non-relational database storage systems for high throughput.",
    duration: "4 Months",
    level: "Beginner to Intermediate",
    emoji: "🗄️",
    syllabus: [
      "Relational Database Design & Schema Creation",
      "Structured Query Language (SQL) Advanced Queries",
      "NoSQL Databases (MongoDB, Cassandra)",
      "Database Indexing & Performance Tuning",
      "Transactions, ACID Properties, and Concurrency",
      "Backup, Recovery, and Replication Strategies",
    ],
  },
  {
    title: "Networking",
    description: "Configure switches, routers, and secure networks for large enterprises and setups.",
    duration: "4 Months",
    level: "Beginner to Intermediate",
    emoji: "🌐",
    syllabus: [
      "TCP/IP and OSI Networking Reference Models",
      "IP Addressing, Subnetting, and Routing Concepts",
      "Switching Basics, VLANs, and Spanning Tree Protocol",
      "Routing Protocols (OSPF, BGP, RIP)",
      "Network Address Translation (NAT) & Firewalls",
      "Introduction to CCNA standards & certification",
    ],
  },
  {
    title: "Software Engineering",
    description: "Learn methodologies, architecture design patterns, and engineering practices used in tech industries.",
    duration: "5 Months",
    level: "Intermediate",
    emoji: "⚙️",
    syllabus: [
      "Software Development Lifecycle (SDLC) & Agile",
      "System Architecture & Object-Oriented Design",
      "Design Patterns (Singleton, Factory, MVC)",
      "Unit Testing, Integration Testing, and TDD",
      "CI/CD Pipelines & Version Control (Git)",
      "Code Refactoring & Technical Debt Management",
    ],
  },
  {
    title: "Artificial Intelligence",
    description: "Understand Natural Language Processing, computer vision, and build Large Language Model applications.",
    duration: "8 Months",
    level: "Advanced",
    emoji: "🔮",
    syllabus: [
      "Introduction to AI & Search Algorithms",
      "Natural Language Processing (NLP) foundations",
      "Computer Vision & Object Detection",
      "Large Language Models (LLMs) & Prompts",
      "LangChain & Vector Databases (Pinecone, Chroma)",
      "AI Ethics, Bias, and Future Technologies",
    ],
  },
  {
    title: "Blockchain Development",
    description: "Code smart contracts, develop decentralized applications (DApps), and understand cryptography.",
    duration: "5 Months",
    level: "Advanced",
    emoji: "⛓️",
    syllabus: [
      "Blockchain Cryptography & Distributed Ledgers",
      "Ethereum, Solidity Smart Contract Syntax",
      "Web3.js & Ethers.js frontend integration",
      "Decentralized Application (DApp) development",
      "Tokens (ERC-20, ERC-721 NFTs) & DeFi Basics",
      "Smart Contract Auditing & Security Vulnerabilities",
    ],
  },
  {
    title: "DevOps",
    description: "Automate build deployments, manage server configurations, and setup monitoring systems.",
    duration: "4 Months",
    level: "Intermediate",
    emoji: "🚀",
    syllabus: [
      "DevOps Culture & Agile Operations",
      "Continuous Integration & Deployment (Jenkins, Actions)",
      "Infrastructure as Code (IaC) with Terraform",
      "Configuration Management using Ansible",
      "Server Monitoring (Prometheus, Grafana)",
      "Log aggregation and analytics (ELK Stack)",
    ],
  },
  {
    title: "Python Programming",
    description: "Learn the most popular language for scripting, automation, web applications, and analytics.",
    duration: "3 Months",
    level: "Beginner to Advanced",
    emoji: "🐍",
    syllabus: [
      "Python Basics: Variables, Loops, and Functions",
      "Object-Oriented Programming (OOP) in Python",
      "File I/O, Error Handling, and Libraries",
      "Interacting with Web APIs and JSON",
      "Automation scripts & web scraping with BeautifulSoup",
      "Writing Clean Code (PEP 8 Standards)",
    ],
  },
  {
    title: "Java Development",
    description: "Develop enterprise-scale backend web services using Java and Spring Boot framework.",
    duration: "6 Months",
    level: "Intermediate",
    emoji: "☕",
    syllabus: [
      "Java Language syntax, OOP, and Collections",
      "Multi-threading & Exception Handling",
      "Spring Boot Framework & Spring MVC",
      "Spring Data JPA & Hibernate ORM mapping",
      "Microservices Architecture & REST API Security",
      "Testing with JUnit and Mockito",
    ],
  },
  {
    title: "C & C++ Programming",
    description: "Understand low-level memory layout, pointers, and high-performance programming techniques.",
    duration: "4 Months",
    level: "Beginner to Advanced",
    emoji: "👾",
    syllabus: [
      "Basic syntax, Control structures & Functions",
      "Pointers, References, and Memory Management",
      "Object-Oriented Programming in C++",
      "Standard Template Library (STL) Containers",
      "Basic Data Structures (Stacks, Queues, Trees)",
      "Algorithms (Sorting, Binary Search, Big-O)",
    ],
  },
];
